const Database = require('better-sqlite3');
const path = require('path');

const db = new Database(path.join(__dirname, 'leads.db'));
db.pragma('journal_mode = WAL');

db.exec(`
  CREATE TABLE IF NOT EXISTS leads (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    date TEXT,
    company TEXT NOT NULL,
    address TEXT,
    contact TEXT,
    email TEXT,
    phone TEXT,
    city TEXT,
    sys4 TEXT,
    appointment_completed TEXT,
    proposal TEXT,
    rs_dollar REAL,
    rm_dollar REAL,
    won INTEGER DEFAULT 0,
    lost INTEGER DEFAULT 0,
    notes TEXT,
    created_at TEXT DEFAULT (datetime('now')),
    updated_at TEXT DEFAULT (datetime('now'))
  )
`);

const stmt = db.prepare(`
  INSERT INTO leads (date, company, address, contact, email, phone, city, sys4, appointment_completed, proposal, rs_dollar, rm_dollar, won, lost, notes)
  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`);

const insertMany = db.transaction((leads) => {
  for (const l of leads) {
    stmt.run(l.date, l.company, l.address, l.contact, l.email, l.phone, l.city, l.sys4, l.appointment_completed, l.proposal, l.rs_dollar, l.rm_dollar, l.won, l.lost, l.notes);
  }
});

const leads = [
  { date: "2025-08-13", company: "Olde Towne Fitness", address: "66 Parsons Ave, Columbus, OH 43215", contact: "Korkeya", email: "korkeya@oldetowneftiness.com", phone: "+1 614-817-1443", city: "Columbus", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Got a call back from Korkeya, the gym owner. He\'s interested in getting quotes; however, he is currently out of the state, and he\'d like to do the walkthrough virtually, via Zoom, for now, which is on Wednesday, August 13, at 2PM. He has a company that comes twice a week, and he\'s looking to add service with 1800 cleanable space. He\'s interested in bathrooms and floor cleaning. We should call him to confirm about our walkthrough a day or hours before. Also asked that we should call him so we can get access to the door remotely. His direct line is 6148321340." },
  { date: "2025-08-11", company: "Fun City Adventure Park", address: "2570 Bethel Rd, Columbus, OH 43220", contact: "Dennis", email: "funcitycolumbus@gmail.com", phone: "614-525-0219", city: "Columbus", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Dennis, general manager, would like to get a cleaning estimate. They currently do their cleaning daily. Not sure of the exact footage, but asked if we can come and do the measurement during the meeting. Also asked that we come on Monday, August 11, at 11 am." },
  { date: "2025-08-21", company: "Covedale Treatment Services", address: "5122 Glencrossing Way, Cincinnati, OH 45238", contact: "Lushinda/ Shaney", email: "admissions@pinnacletreatment.com", phone: "+1 513-827-9044", city: "Cincinnati", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Spoke with Lushinda, Medical Nursing Supervisor. Said that we can visit them at the center for a walkthrough on Thursday, at 11 am, and advise us to speak with Shaney Owen, their Director. They do work with an outside company but she can\'t remember the name of the provider. She said to discuss everything when we come around on Thursday." },
  { date: "2025-09-02", company: "The Cabinet Shop Distribution & Design, Inc", address: "9075 Antares Avenue, Columbus, OH 43240", contact: "Hans Jurawitz/Kaitlyn", email: "hans@thecabshop.com", phone: "614-885-9676", city: "Columbus", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Contacted Hans about our intention to provide a cleaning estimate. He would like us to come visit them for a quote. They require their cleaning once a week. Their facility area is unknown, but we can take the measurement during the meeting. We will be meeting with Kaitlyn to have her show us around." },
  { date: "2025-09-03", company: "Menards", address: "1805 Morse Rd Service Road, Columbus, OH 43229", contact: "Ian Wimmers", email: "clbsgeneralmanager@menards.com", phone: "+1 614-262-7354", city: "Columbus", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Dialed ext 22 and spoke with Ian Wimmers, the General Manager. He is interested in getting quotes and available for the walkthrough on Wednesday, September 3, 2025 at 2 pm. They currently work with an outside provider daily and he is new there. The cleanable space is larger than 1500 sq ft." },
  { date: "2025-09-10", company: "INTACT COUNSELING", address: "9200 Montgomery Road Building D Suite 15B Cincinnati, Ohio 45242", contact: "Sharon R. Frankart", email: "sharon.frankart@intact.hush.com", phone: "(513) 600-2554", city: "Cincinnati", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Sharon would like to get a cleaning estimate. They are taking bids. She would like to meet us on Wednesday at 1 pm. Attached is their scope of work." },
  { date: "2025-09-11", company: "ALL iN GOLF", address: "8182 Beechmont Ave, Cincinnati, OH 45255", contact: "Ken", email: "info@allingolf513.com", phone: "513-474-4653", city: "Cincinnati", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Ken would like to get a cleaning estimate. They are currently accepting bids and require weekly service. Agreed to meet on Thursday, September 11th at 11 am" },
  { date: "2025-09-24", company: "Westside Academy of Gymnastics", address: "5775 Filview Cir, Cincinnati, OH 45248", contact: "Kim", email: "Westsideacademyofgymnastics@gmail.com", phone: "513-574-0444", city: "Cincinnati", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Kim, Owner, would like to get a cleaning estimate. They have a company that comes 3x a week. Their facility is larger than 3,000 sq ft. Agreed to meet on September 24th at 4pm- her available time." },
  { date: "2025-09-25", company: "Milkman", address: "1106 Race St, Cincinnati, OH 45202", contact: "Kate Horner", email: "paul.folker@milkmanbar.com", phone: "+1 513-381-0009", city: "Cincinnati", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Spoke with Kate, the General Manager. She\'s interested in getting quotes and available for the walk-through on Thursday, September 25, 2025 at 10:30 am. They do their cleaning pretty much everyday. She\'s horrible about the square feet of their facility though, so we can take measurements during the meeting" },
  { date: "2025-09-23", company: "The Music Salon", address: "6919 Miami Ave, Cincinnati, OH 45243", contact: "Sean McGary", email: "sean@themusicsalon.com", phone: "+1 513-708-2497", city: "Cincinnati", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Sean would like to get a cleaning estimate. They are taking bids for weekly cleaning. He would like to meet on Tuesday, the 23rd at 11 am" },
  { date: "2025-09-29", company: "The Capital Grille", address: "Lennox Center- 1827 Olentangy River Rd, Columbus, OH 43212", contact: "Matt Walker", email: "columbus@tcgdine.com", phone: "+1 614-453-2760", city: "Columbus", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Spoke with Matt, the General Manager. He\'s available for the visit on Monday, September 29, 2025 at 3:30 PM. They do work with a provider that cleans every night including weekends. He said he is interested in cleaning all aspect of the restaurant- front, back and kitchen as well as kitchen equipments. He\'s unsure of the exact sq ft but its quite big and not an ordinary restaurant, he added." },
  { date: "2025-10-02", company: "Buca di Beppo Italian Restaurant", address: "2635 Edmondson Rd, Norwood, OH 45209", contact: "Sam Hatsield / Freddy", email: null, phone: "+1 513-396-7673", city: "Norwood", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Spoke with Freddy, the Assistant. He would like to get a cleaning estimate. Suggested that we come on Thursday at 3 pm. They do work with a cleaning company that cleans quarterly but would like to get a once to twice a week service proposals. He\'s unsure of the exact sq ft they have but told me that the area is a pretty big space. He said we would also be meeting with Sam- general manager." },
  { date: "2025-09-30", company: "SOLHAUS", address: "15 W 14th St. Floor 2 Cincinnati, OH 45202", contact: "Amy", email: "sol@solhausotr.com", phone: "+1 513-201-7356", city: "Cincinnati", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Amy would like to get a cleaning estimate. They are taking bids for their weekly cleaning. Asked if we can come tomorrow closer to 11:45-12 noon." },
  { date: "2025-10-06", company: "Makley Place", address: "210 W 5th Ave, Columbus, OH 43201", contact: "Cam/ Rahim", email: "mak@villagegreen.com", phone: "+1 614-881-4328", city: "Columbus", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Spoke with Mak said that we can visit their facility for an estimate on Monday, October 6 at 11 am. They do work with a company that comes once a week and next year, in January they would be doing a new budget for cleaning by then. However, he would like to meet us for the estimate. They have lobbies, bathrooms, etc. We would be meeting with Rahim as well." },
  { date: "2025-10-08", company: "Gahanna Lanes", address: "215 W Johnstown Rd, Gahanna, OH 43230", contact: "Lorenzo Jones", email: "gahannalanes@gmail.com", phone: "+1 614-471-1111", city: "Gahanna", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Spoke with Lorenzo, general manager. He\'d like to get a quote. He\'s available for the visit on Wednesday, October 8 at 1pm. They do their cleaning at the moment and might require three times a week. They have a huge facility but the cleanable space is 4,000 sq ft." },
  { date: "2025-10-13", company: "Menards", address: "6800 E Broad St, Columbus, OH 43213", contact: "Jeremiah Shiveoy", email: "dolegeneralmanager@menards.com", phone: "+1 614-501-1654", city: "Columbus", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Spoke with Jeremiah, one of the General Managers. Said that they always open for bids. And he\'s available for the walkthrough on Monday October 13, 2025 at 11 AM. They have a provider that comes once a day for the restrooms, cleanable space is just lesser than 2,000 sq ft." },
  { date: "2025-10-17", company: "Sur-Seal LLC", address: "6156 Wesselman Rd, Cincinnati, OH 45248", contact: "Bob", email: null, phone: "+1 513-574-8500", city: "Cincinnati", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Bob would like to get a cleaning estimate. They require their cleaning 2x a week. He will be out starting tomorrow until next Thursday. Agreed to meet on the 17th at 11 am" },
  { date: "2025-10-21", company: "Casco Manufacturing Solutions Inc.", address: "3107 Spring Grove Ave, Cincinnati, OH 45225", contact: "Jeff", email: null, phone: "+1 513-681-0003", city: "Cincinnati", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Jeff said we can come visit them for a cleaning estimate. They have a company that comes weekly. He said, he will be swamped for a week- but set tentatively on the 21st of October. Said we could call him to confirm on Monday, the 20th." },
  { date: "2025-10-14", company: "American Metal Supply Co.", address: null, contact: "Mason", email: "mreynolds@amsupplyco.com", phone: "513-396-6600 ext 3744", city: null, sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Spoke with Mason. He would like to take a cleaning estimate. They have company that comes once a week. Cleanable area is lower than 5,000 sq ft. Agreed to meet on Tuesday at 11 am for an estimate." },
  { date: "2025-10-16", company: "About Radius at The Banks", address: "44 West Freedom Way, Cincinnati, OH 45202", contact: "Paris/ Jessica", email: "radius@crawfordhoying.com", phone: "(513) 643-6481", city: "Cincinnati", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Spoke with Paris, the Senior Leasing, told her about the cleaning service we offer and said that we can come through at their facility for an estimate on Thursday, October 16 at 2pm. She will also be informing Jessica about the walkthrough ahead of time, and told me that quote will be sent on the email after which. They do work with a provider that comes five days week. Common areas are their lobby, club room, 24/7 fitness center, and etc. She asks for an info to be sent including the date and time of the visit." },
  { date: "2025-10-17", company: "Dueling Axes - Cincinnati Axe Throwing & Sports Bar", address: "246 W Elder St, Cincinnati, OH 45202", contact: "Geoff", email: null, phone: "513-452-5944", city: "Cincinnati", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Geoff, the general manager, would like to get a cleaning estimate. They do their cleaning daily, and their cleanable area is big. He will be available on the 17th, Friday at 2 pm." },
  { date: "2025-10-16", company: "Tansky Powersports", address: "2491 W Dublin-Granville Rd, Columbus, OH 43235", contact: "Travis Green", email: "travis.green@tanskypowersports.com", phone: "+1 614-362-9037", city: "Columbus", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Spoke with Travis, the GM, and he\'d like to get a quote for review. They clean three days a week. They require once a week of service from another provider with about 10000 sq ft of cleanable space. He agreed to a walkthrough on Thursday, October 16, 2025, at 2 PM." },
  { date: "2025-10-17", company: "Mellow Mushroom New Albany", address: "260 Market St Ste A, New Albany, OH 43054", contact: "Nick", email: null, phone: "+1 614-245-4234", city: "New Albany", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Spoke with Nick, the general manager, and he told me that we visit and provide them an estimate and meet with Colby, the owner, who is the only one in on Friday mornings. They do their own cleaning for the most part. The cleanable space is larger than 2,000 sq ft. They have a pretty large dining room and a decent-sized kitchen. Can meet there on Friday, at 11:30AM. He will be informing Colby about the visit." },
  { date: "2025-10-23", company: "Infinity Pharmacy", address: "2819 Westerville Rd, Columbus, OH 43224", contact: "Rita Oti", email: "infinity.rx.pharmacy@gmail.com", phone: "+1 614-591-3070", city: "Columbus", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Spoke with Rita, the manager. She\'s interested in getting quotes and available for the visit on Thursday, October 23, 2025, at 2PM. They do in-house cleaning at the moment and interested in getting once or twice a week of service proposals with about 1500-2000 sq ft cleanable space" },
  { date: "2025-10-29", company: "CUT132", address: "4188 Brighton Rose Way, Columbus, OH 43219", contact: "Rich Moore", email: "richard.moore@thompsonrestaurant.com", phone: "380-208-6883", city: "Columbus", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Spoke with Rich, the general manager. He would like to take a quote. He said they have a cleaning provider but are open to a quote. The provider comes every day, and the facility is larger than 2,000 sq ft." },
  { date: "2025-11-13", company: "Cleopatra Ink Tattoo & Piercing Columbus Studio", address: "1217 N High St, Columbus, OH 43201", contact: "MEHMET DEMIR", email: null, phone: "+1 614-720-4404", city: "Columbus", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Spoke with Mehmet, studio manager. He\'d like to get a quote. He does have a cleaning company that comes once a week and told me that he will provide other information when we can come in on Thursday at 2 pm" },
  { date: "2025-11-19", company: "Rusk Kitchen and Bar", address: "2724 Woodburn Ave, Cincinnati, OH 45206", contact: "Brian McVey", email: "gm@ruskcincy.com", phone: "513-221-7875", city: "Cincinnati", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Brian, general manager, would like to get a cleaning estimate for their weekly cleaning. He said they just got out of a contract in September and have decided to do things in-house for the winter months. But will be open to looking into a service before the spring weather." },
  { date: "2025-12-09", company: "Tarman Machine Company, INC.", address: "8215 Dove Pkwy Canal Winchester, OH 43110", contact: "Bart", email: null, phone: "6148344010", city: "Canal Winchester", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "I spoke with Bartâthe person in charge of the cleaning services. Said Dan Schecter already provided him a quote but would like to meet us on Tuesday for a quote. They have a cleaning service that comes weekly." },
  { date: "2025-12-12", company: "RollHouse Columbus", address: "500 Georgesville Rd, Columbus, OH 43228", contact: "DREW TATMAN", email: "drew.tatman@therollhouse.com", phone: "+1 614-274-1169", city: "Columbus", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Spoke with Drew, the GM. He\'s interested in getting quotes. He would like to know the timeframe of our service, as he\'d like to get services on weekends. Cleanable space is 1,750. He\'s available on Friday, Dec 12, 2025, at 2:30 PM." },
  { date: "2025-12-16", company: "The Filson Queen City Kitchen & Bar", address: "25 E Freedom Way, Cincinnati, OH 45202", contact: "Gannon Reddy", email: "greddy@thefilson.com", phone: "+1 513-653-6700", city: "Cincinnati", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Spoke with Gannon Reddy, Manager. He\'d like to get a quote and available for the visit on Tuesday, December 16 at 2pm. He would be interested in getting twice a week with around 2000 sq ft area." },
  { date: "2026-01-27", company: "Hyde Park Play School", address: "3846 Drake Ave, Cincinnati, OH 45209", contact: "Jennifer", email: "office@hydeparkplayschool.com", phone: "513-643-0021", city: "Cincinnati", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Jennifer is the center director. She would like us to come and visit them for a cleaning estimate. They have a company that comes once a week. Cleanable area is larger than 2,000 sq ft. Agreed to meet on Tuesday next week, January 27th at 2 pm" },
  { date: "2026-02-17", company: "7 Hills Harley-Davidson", address: "699 Cincinnati-Batavia Pike, Cincinnati, OH 45245", contact: "Tim Ballard", email: "tim.ballard@7hillsharleydavidson.com", phone: "+1 513-528-1400", city: "Cincinnati", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Spoke with Tim, the service manager. He\'d like to get a cleaning quote and will be available on Tuesday, February 17, 2026, at 11 am. They have a company that comes 2x a week. The cleanable space is larger than 5000 sq ft." },
  { date: "2026-02-24", company: "Menards", address: "1805 Morse Rd Service Road, Columbus, OH 43229", contact: "Josh", email: "clbsgeneralmanager@menards.com", phone: "614-262-7354", city: "Columbus", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Spoke with Josh, general manager. He would like to get a cleaning quote. Said they have a company that comes 7 days a week for cleaning. Agreed to meet on February 24th, Tuesday, at 11 am." },
  { date: "2026-02-26", company: "Yard House", address: "95 E Freedom Way, Cincinnati, OH 45202", contact: "Tim", email: null, phone: "513-381-4071", city: "Cincinnati", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Tim would like to get a cleaning estimate. They have a company that comes 2x a week. Agreed to be visited on Thursdayâhis convenient timeâbut asked me to call him a day before to confirm his calendar." },
  { date: "2026-03-03", company: "Menards- Lancaster", address: "1425 ETY POINTE DR NW, LANCASTER, OH 43130", contact: "Nick", email: "lnctgeneralmanager@menards.com", phone: "740-654-3538", city: "Lancaster", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Spoke with Nick, general manager. He would like to get a cleaning estimate. They have a company that comes once on weekdays and two times on Saturdays and Sundays. He\'d like to meet us on Tuesday next week at 11 am" },
  { date: "2026-03-16", company: "VV The Italian Experience", address: "1026 Delta Ave, Cincinnati, OH 45208", contact: "Melissa Tesano", email: "mtlookout@vvitalian.com", phone: "513-485-4007", city: "Cincinnati", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Spoke with Melissa, the owner. She would like to get a cleaning estimate. Said require their cleaning once a week. She is interested; however, she will be in Italy in the next 2 weeks. She asked if we can come on Monday, March 16th at 11 am" },
  { date: "2026-03-05", company: "Jeff Wyler Superior Honda", address: "4777 Spring Grove Ave, Cincinnati, OH 45232", contact: "Drew P.", email: null, phone: "513-401-8908", city: "Cincinnati", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Drew would like to get a cleaning estimate. They have a company that comes 5 days a week. Agreed to meet on Thursday, March 5th, at 11 am. He\'ll be out this week." },
  { date: "2026-03-02", company: "Champions Golf Course", address: "3900 Westerville Rd, Columbus, OH 43224", contact: "Dave", email: "djwehner@columbus.gov", phone: "614-645-7111", city: "Columbus", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Spoke with Dave, general manager. He said they do their regular cleaning. He would like to get a cleaning estimate. He would also get an estimate for their restaurant. Agreed to meet on March 2, Monday at 10 am" },
  { date: "2026-03-03", company: "Mentel Memorial Golf Course", address: "6005 Alkire Rd, Galloway, OH 43119", contact: "Joe", email: null, phone: "6143130045", city: "Galloway", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Joe, the general manager, reached out to us to get a cleaning estimate for their restrooms. He would be available on Tuesday, March 3rd, at 11 am" },
  { date: "2026-03-04", company: "Menards-LOVELAND", address: "3787 W STATE ROUTE 223, LOVELAND, OH 45140", contact: "Spencer/ Tyler/ Paul", email: null, phone: "513-583-1444", city: "Loveland", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Spoke with Spencer, general manager. He said they have a company that does their cleaning 7 days a week. He\'d like to meet on Wednesday at 2 pm. If he\'s not there, we should ask for his assistants Tyler or Paul." },
  { date: "2026-02-24", company: "Hub Cincinnati", address: "350 Straight St, Cincinnati, OH 45219", contact: "Brittney", email: "bribrown@corespaces.com", phone: "513-916-2541", city: "Cincinnati", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Brittney, the property manager, would like to get a cleaning estimate. They have a company that comes 7 days a week to clean their common areas like their clubhouse, fitness center, offices, and bathrooms." },
  { date: "2026-03-04", company: "Alcove by MadTree Brewing", address: "1410 Vine St, Cincinnati, OH 45202", contact: "Derick", email: null, phone: "513-371-5700", city: "Cincinnati", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Derick would like to get a cleaning estimate. They do their cleaning every day. Said that he will be out of town for a couple of weeks, so suggested that we come in March and set the meeting on March 4th, Wednesday, at 2 pm." },
  { date: "2026-03-24", company: "Menards - LEWIS CENTER", address: "7241 GRAPHICS WAY, LEWIS CENTER, OH 43035", contact: "Brayden", email: "lewigeneralmanager@menards.com", phone: "740-548-6735", city: "Lewis Center", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Spoke with Brayden, general manager. He would like to get a cleaning estimate. They have a company that comes 7 days a week. Agreed to meet on March 24th at 11 am" },
  { date: "2026-03-24", company: "Balanced Family Academy of Harrison West", address: "870 Michigan Ave, Columbus, OH 43215", contact: "Katie", email: "katie.buscemi@bfa.care", phone: "(614) 824-4666", city: "Columbus", sys4: null, appointment_completed: null, proposal: null, rs_dollar: null, rm_dollar: null, won: 0, lost: 0, notes: "Spoke with Katie, director. She would like to get a cleaning estimate. They have a company that comes 5 days a week. Monday-Friday. She agreed to meet on Tuesday at 11 am" },
];

// Clear existing and seed
db.exec('DELETE FROM leads');
insertMany(leads);
console.log(`Seeded ${leads.length} leads successfully!`);
db.close();
